# Generated by Django 4.1.4 on 2023-01-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_announcement_announcer_location_photo_delete_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcer',
            old_name='adress',
            new_name='address',
        ),
    ]
