# Generated by Django 4.1.4 on 2023-01-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_announcement_location_announcement_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='modality',
            field=models.BooleanField(default=False),
        ),
    ]
