# Generated by Django 4.1.4 on 2023-01-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_announcement_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcer',
        ),
    ]
