# Generated by Django 4.1.4 on 2023-01-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_announcer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='announcement',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
