# Generated by Django 4.1.4 on 2023-01-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_announcement_photo_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='wilaya',
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=50, null=True)),
                ('commune', models.CharField(max_length=50, null=True)),
                ('adresseExa', models.CharField(max_length=200, null=True)),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='blog.announcement')),
            ],
            options={
                'unique_together': {('announce', 'wilaya', 'commune', 'adresseExa')},
            },
        ),
    ]
