# Generated by Django 4.1.4 on 2023-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_announcement_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='commune',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='latitude',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='longitude',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='wilaya',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
