# Generated by Django 4.1.4 on 2023-01-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_announcement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
